<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="index.html"><i class="fa fa-home"></i> Home</a> / <a href="contact.html">Contact us</a>
		</div>
	</div>
</div>


<section class="contact-us text-center">
	<div class="container">
		<h3 class="section-header">Get in touch</h3>
		<div class="col-md-7 text-left">
			<form class="contact-form" method="POST">
				<input type="text" class="contact-input" placeholder="Name" required>
				<input type="email" class="contact-input"  placeholder="Email" required>
				<input type="text" class="contact-input" placeholder="Subject" required>
				<textarea class="contact-input" placeholder="Message" required></textarea>
				<button type="submit" class="contact-btn"><i class="fa fa-send"></i> Send</button>
			</form>
		</div>
		<div class="col-md-5 contact-info text-left">
			<h3>Libero Inc.</h3>
			<p><i class="fa fa-map-marker"></i> 1, Lvivska str., Ternopil, Ukraine</p>
			<p><i class="fa fa-phone"></i> +38 (032) 534-43-21</p>
			<p><i class="fa fa-envelope"></i> contact@libero.com</p>
		</div>
	</div>
	<hr>

	<div class="container">
		<iframe width="100%" height="400" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?q=place_id:ChIJ-UX3WdA2MEcRHHnJT8akBwU&key=AIzaSyBFkgl4ke4BQWWVEydhVXrSXEIcSpbjOQI" allowfullscreen></iframe>
	</div>
</section>