<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/"><i class="fa fa-home"></i> Home</a> / <a href="/search">Search</a>
		</div>
	</div>
</div>

<div class="container">
	<h2><i class="fa fa-search" style="margin-right:10px"></i> Search results for &laquo;<?php echo $this->query ?>&raquo;</h2>
	<?php if (count($this->results)!=0): ?>
		<?php for ($i = 0; $i < count($this->results); $i++): ?>
		<?php if ($i%4 == 0 && $i != 0): ?>
		</div>
		<?php endif; ?>
		<?php if($i%4 == 0): ?>
		<div class="row">
			<?php endif; ?>
			<div class="col-md-3">
				<div class="product-card">
					<a href="/catalogue/view/id/<?php echo $this->escape($this->results[$i]['id']) ?>" class="product-view"><i class="fa fa-search-plus"></i> Quick view</a>
					<img src="/img/products/<?php echo $this->escape($this->results[$i]['photo']) ?>">
					<div class="product-info">
						<h5><?php echo $this->escape($this->results[$i]['title']) ?></h5>
						<p><?php echo $this->escape($this->results[$i]['description']) ?></p>
						<hr>
						<div class="clearfix">
							<div class="pull-left product-price">$<?php echo $this->escape($this->results[$i]['price']) ?></div>
							<div class="pull-right product-add-cart"><a href="#"><i class="fa fa-shopping-cart"></i> Add to cart</a></div>
						</div>
					</div>
				</div>
			</div>
		<?php endfor; ?>
	<?php else: ?>
		<h1 class="not-found">Unfortunately, no results were found</h1>
	<?php endif; ?>
</div>
</div>