<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/"><i class="fa fa-home"></i> Home</a> / <a href="/auth">Account</a>
		</div>
	</div>
</div>

<section class="account">
	<div class="container">
		<div class="col-md-4 col-lg-4 sidebar">
			<h1><?php echo $this->userName ?></h1>
			<p>User ID: <?php echo $this->userId ?></p>
			<hr noshade>
			<a href="/auth/edit"><i class="fa fa-pencil"></i> Edit personal info</a>
			<hr noshade>
			<a href="/auth/orders"><i class="fa fa-list"></i> Orders in progress</a>
			<hr noshade>
			<?php if($this->userRole == "admin"): ?>
			<a href="/admin" target="_blank"><i class="fa fa-lock"></i> Admin section</a>
			<hr noshade>
			<?php endif; ?>
			<a href="/auth/logout"><i class="fa fa-sign-out"></i> Logout</a>
		</div>
		<div class="col-md-8 col-lg-8">

		</div>
	</div>
</section>