<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/"><i class="fa fa-home"></i> Home</a> / <a href="/login">Login</a>
		</div>
	</div>
</div>


<div class="login-box text-left">
	<div class="login-form center-block">
		<?php if($this->errMessage): ?>
		<div class="alert alert-danger">
			<?php echo $this->errMessage ?>
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		</div>
		<?php endif; ?>
		<h4>Log in</h4>
		<p>If you already have an account, please log in</p>
		<?php echo $this->form; ?>
	</div>
</div>