<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/"><i class="fa fa-home"></i> Home</a> / <a href="/register">Register</a>
		</div>
	</div>
</div>

<div class="login-box text-left">
	<div class="login-form center-block">
		<?php if($this->errMessage): ?>
			<div class="alert alert-danger">
				<?php echo $this->errMessage ?>
				<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			</div>
		<?php endif; ?>
		<h4>Sign up</h4>
		<p>By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more</p>
		<?php echo $this->form; ?>
	</div>
</div>
