<?php
$homeUrl = $this->url(array('controller' => 'admin', 'action' => 'index'));
$productsUrl = $this->url(array('controller' => 'admin', 'action' => 'showproducts'));
$categoriesUrl = $this->url(array('controller' => 'admin', 'action' => 'showcategories'));
$ordersUrl = $this->url(array('controller' => 'admin', 'action' => 'showorders'));
$addProductUrl = $this->url(array('controller' => 'admin', 'action' => 'addproduct'));
$addCategoryUrl = $this->url(array('controller' => 'admin', 'action' => 'addcategory'));

$this->headTitle()->setSeparator(' | ');
$this->headTitle('Admin Libero');
echo $this->doctype();
?>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width initial-scale=1.0">
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/style.css'); ?>
    <?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/bootstrap.css'); ?>
    <?php echo $this->headLink()->setStylesheet($this->baseUrl().'/css/font-awesome.min.css'); ?>
    <link rel="shortcut icon" href=""/>
    <?php echo $this->headScript()->setFile($this->baseUrl().'/js/jquery.js'); ?>
    <?php echo $this->headScript()->setFile($this->baseUrl().'/js/jquery-ui.js'); ?>
    <?php echo $this->headScript()->setFile($this->baseUrl().'/js/bootstrap.js'); ?>
    <?php echo $this->headScript()->setFile($this->baseUrl().'/js/main.js'); ?>
    <?php echo $this->headScript()->setFile('https://www.google.com/recaptcha/api.js'); ?>
</head>
<body>
<!-- navbar nav -->
<nav class="navbar navbar-default">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $homeUrl ?>"><img src="/img/admin_logo.png" alt="Logo"></a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-left">
                <li><a href="/admin">Home</a></li>
                <li><a href="/admin/showproducts">Products</a></li>
                <li><a href="/admin/showcategories">Categories</a></li>
                <li><a href="/admin/showorders">Orders</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Add <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="<?php echo $addProductUrl ?>">Product</a></li>
                        <li><a href="<?php echo $addCategoryUrl ?>">Category</a></li>
                    </ul>
                </li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                <li><a href="<?php echo $ordersUrl ?>" title="New orders"><i class="fa fa-bell"></i> <?php echo $this->activeOrdersCount ?></a></li>
                <li><a href="/"><i class="fa fa-sign-out"></i> Back to website</a></li>
            </ul>
        </div>
    </div>
</nav>
<?php echo $this->layout()->content ?>