<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/admin"><i class="fa fa-home"></i> Admin</a> / <a href="/admin/showproducts">Products</a> / <a href="/addproduct">Add</a>
		</div>
	</div>
	<?php var_dump($this->file) ?>
	<div class="add-box login-box text-left">
		<div class="login-form">
			<?php if($this->errMessage): ?>
				<div class="alert alert-danger">
					<?php echo $this->errMessage ?>
					<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
				</div>
			<?php endif; ?>
			<h4>Add product</h4>
			<?php echo $this->form; ?>
		</div>
	</div>
</div>