<?php
$statuses = array('Inactive', 'Active', 'In progress', 'Completed');
$status = intval($this->order['status']);
?>
<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/admin"><i class="fa fa-home"></i> Admin</a> / <a href="/admin/showorders">Orders</a> / <a href="/admin/editorder/id/1">Order #<?php echo $this->order['id'] ?></a>
		</div>
	</div>

	<h3>Order information</h3>
	<table class="table">
		<tr>
			<th>ID:</th>
			<td><?php echo $this->order['id'] ?></td>
		</tr>
		<tr>
			<th>Name:</th>
			<td><?php echo "{$this->order['first_name']} {$this->order['last_name']}" ?></td>
		</tr>
		<tr>
			<th>Date:</th>
			<td><?php echo $this->order['date'] ?></td>
		</tr>
		<tr>
			<th>Phone:</th>
			<td><?php echo $this->order['phone'] ?></td>
		</tr>
		<tr>
			<th>Email:</th>
			<td><?php echo $this->order['email'] ?></td>
		</tr>
		<tr>
			<th>Comment:</th>
			<td><?php echo $this->order['comment'] ?></td>
		</tr>
		<tr>
			<th>Total price:</th>
			<td>2131</td>
		</tr>
		<tr>
			<th>Status:</th>
			<td>
				<select id="status-select" onchange="changeStatus(<?php echo $this->order['id'] ?>)">
					<?php for ($i = 0; $i < count($statuses); $i++): ?>
						<?php if ($i === $status): ?>
							<option selected><?php echo $statuses[$i] ?></option>
						<?php else: ?>
							<option><?php echo $statuses[$i] ?></option>
						<?php endif; ?>
					<?php endfor; ?>
				</select>
			</td>
		</tr>
	</table>

	<h4>Items in order</h4>
	<table class="table table-responsive table-hover">
		<?php foreach ($this->items as $item): ?>
			<tr>
				<td><?php echo $item['id'] ?></td>
				<td><?php echo $item['title'] ?></td>
				<td><?php echo $item['price'] ?></td>
				<td><?php echo $item['description'] ?></td>
				<td><?php echo $item['brand'] ?></td>
				<td><?php echo $item['size'] ?></td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>