<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/admin"><i class="fa fa-home"></i> Admin</a> / <a href="/admin/showproducts">Products</a>
		</div>
	</div>
	<a href="/admin/addproduct" class="login-btn pull-left"><i class="fa fa-plus"></i> Add</a>

	<table class="table table-hover table-responsive">
		<tr>
			<th>ID</th>
			<th>Title</th>
			<th>Price</th>
			<th>Description</th>
			<th>Brand</th>
			<th>Size</th>
			<th>Actions</th>
		</tr>
		<?php foreach($this->products as $product): ?>
			<tr>
				<td><?php echo $product['id'] ?></td>
				<td><?php echo $product['title'] ?></td>
				<td><?php echo $product['price'] ?></td>
				<td><?php echo $product['description'] ?></td>
				<td><?php echo $product['brand'] ?></td>
				<td><?php echo $product['size'] ?></td>
				<td>
					<a href="/admin/editproduct/id/<?php echo $product['id'] ?>" title="Edit"><i class="fa fa-pencil"></i></a>
					<a href="javascript:deleteProduct(<?php echo $product['id'] ?>)" title="Delete"><i class="fa fa-remove"></i></a>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>