<?php
$statuses = array('Inactive', 'Active', 'In progress', 'Completed');
?>
<div class="container">
	<div class="path clearfix">
		<div class="pull-left text-left">
			<a href="/admin"><i class="fa fa-home"></i> Admin</a> / <a href="/admin/showorders">Orders</a>
		</div>
	</div>

	<table class="table table-hover table-responsive">
		<tr>
			<th>ID</th>
			<th>Customer Name</th>
			<th>Date</th>
			<th>Phone</th>
			<th>Email</th>
			<th>Comment</th>
			<th>Status</th>
			<th>Actions</th>
		</tr>
		<?php foreach($this->orders as $order): ?>
			<tr>
				<td><?php echo $order['id'] ?></td>
				<td><?php echo "{$order['first_name']} {$order['last_name']}" ?></td>
				<td><?php echo $order['date'] ?></td>
				<td><?php echo $order['phone'] ?></td>
				<td><?php echo $order['email'] ?></td>
				<td><?php echo $order['comment'] ?></td>
				<td><?php echo $statuses[$order['status']] ?></td>
				<td>
					<a href="/admin/editorder/id/<?php echo $order['id'] ?>" title="Edit"><i class="fa fa-pencil"></i></a>
					<a href="javascript:deleteOrder(<?php echo $order['id'] ?>)" title="Delete"><i class="fa fa-remove"></i></a>
				</td>
			</tr>
		<?php endforeach; ?>
	</table>
</div>